### ISSUE TITLE
Scripts need to handle HTTP 500 errors gracefully

### ISSUE THREAD

**Issue by jcgoble3** [jcgoble3/AJTD6#3]
```
ERROR: Task "forumarchive" encountered an unhandled error and failed at August 3, 2015, 00:00:06 UTC
Error details: HTTP Error 500: Internal Server Error
Traceback (most recent call last):
  File "./master.py", line 41, in <module>
    task.main(wook, log_info, log_error)
  File "/home/jcgoble3/scripts/bots/wookieepedia/tasks/forumarchive.py", line 114, in main
    data = wook.call(query)
  File "/usr/local/lib/python3.4/dist-packages/simplemediawiki.py", line 184, in call
    return json.loads(self._fetch_http(self._api_url, params))
  File "/usr/local/lib/python3.4/dist-packages/simplemediawiki.py", line 156, in _fetch_http
    response = self._opener.open(request)
[extended traceback snipped]
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
```

This happens on occasion and should be handled properly by catching the error and retrying the request after an appropriate amount of waiting time. In an ideal world, the underlying framework should handle it automatically "behind the scenes", but simplemediawiki doesn't. (Hopefully basicmediawiki, whenever I finish it, will.)

Not sure whether it would be better to write this error handling into the individual task scripts, or to fork and modify simplemediawiki itself. (Better yet would be to get off my lazy ass and bring basicmediawiki up to a usable state, so I can abandon simplemediawiki completely. :P)

**Comment by jcgoble3** [comment]
This is starting to happen more often. Three errors in three consecutive runs, two produced by `forumarchive` and one by `verifytouch`. Something needs to be done soon.

**Comment by jcgoble3** [comment]
The pull requests above ought to prevent total failures because of server flakiness, yet still raise the error if it's down completely. Thus, I think this is closed.
